/**********************************************************************/
/*                                                                    */
/*             FILENAME:  order.h                                     */
/*             BY:  Jonathan G. Fiscus                                */
/*                  NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY    */
/*                  SPEECH RECOGNITION GROUP                          */
/*                                                                    */
/*           DESC:  This file contains defines for ordering arrays    */
/*                                                                    */
/**********************************************************************/
#define DECREASING	1
#define INCREASING	0
