/* the main sphere include file 
 */

#include <util/chars.h>
#include <util/fob.h>
#include <util/min.h>
#include <util/hsgetopt.h>
#include <util/err_util.h>
#define MTRF_ON
#include <util/mtrf.h>
#include <sp/header.h>
#include <sp/sysparam.h>
#include <sp/sysfunc.h>
#include <sp/spchksum.h>

#include <sp/spfile.h>
#include <sp/sp.h>
#include <sp/shorten/shrt_sph.h>
#include <sp/wavpack/wavpack.h>
#include <sp/version.h>

