/***********************************************************************/
/*    File: shrt_sph.h                                                 */
/*    Desc: Sphere to Shorten interface header file                    */
/*    History:                                                         */
/*        Mar 29, 1993:  Creation                                      */
/***********************************************************************/

extern int shortpack_compress();
extern int shortpack_uncompress();


